development:
  adapter: postgresql
  database: app_name_development
  username: cool_user
  password: qburst
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: app_name_test
  username: cool_user
  password: qburst
  encoding: unicode
  host: localhost
  pool: 5

